language: c
sudo: required
dist: trusty
services:
  - docker

env:
    global:
        - BLAS=openblas
        - PLAT=x86_64
        - SCRIPT=build_stack.sh
        - CYTHON_VERSIONS="0.24"
        - NUMPY_VERSIONS="1.11.1rc1"
        - SCIPY_VERSIONS="0.17.1"
        - SCIKIT_LEARN_VERSIONS="0.17.1"
        - PANDAS_VERSIONS="0.18.0"
        - NUMEXPR_VERSIONS="2.5.1"
        - STATSMODELS_VERSIONS="0.6.1"
        - SCIKIT_IMAGE_VERSIONS="0.12.3"
        - MATPLOTLIB_VERSIONS="2.0.0b1"

matrix:
  include:
    - env:
        - PY_VER=2.7
    - env:
        - PY_VER=3.4
    - env:
        - PY_VER=3.5
    - env:
        - UNICODE_WIDTH=16
        - PY_VER=2.7
    - env:
        - PY_VER=2.7
        - PLAT=i686
    - env:
        - PY_VER=3.4
        - PLAT=i686
    - env:
        - PY_VER=3.5
        - PLAT=i686
    - env:
        - UNICODE_WIDTH=16
        - PY_VER=2.7
        - PLAT=i686
    - env:
        - PY_VER=2.7
        - SCRIPT=build_skimages.sh
    - env:
        - PY_VER=3.4
        - SCRIPT=build_skimages.sh
    - env:
        - PY_VER=3.5
        - SCRIPT=build_skimages.sh
    - env:
        - UNICODE_WIDTH=16
        - PY_VER=2.7
        - SCRIPT=build_skimages.sh
    - env:
        - PY_VER=2.7
        - PLAT=i686
        - SCRIPT=build_skimages.sh
    - env:
        - PY_VER=3.4
        - PLAT=i686
        - SCRIPT=build_skimages.sh
    - env:
        - PY_VER=3.5
        - PLAT=i686
        - SCRIPT=build_skimages.sh
    - env:
        - UNICODE_WIDTH=16
        - PY_VER=2.7
        - PLAT=i686
        - SCRIPT=build_skimages.sh
    - env:
        - PY_VER=2.7
        - SCRIPT=build_matplotlibs.sh
    - env:
        - PY_VER=3.4
        - SCRIPT=build_matplotlibs.sh
    - env:
        - PY_VER=3.5
        - SCRIPT=build_matplotlibs.sh
    - env:
        - UNICODE_WIDTH=16
        - PY_VER=2.7
        - SCRIPT=build_matplotlibs.sh
    - env:
        - PY_VER=2.7
        - PLAT=i686
        - SCRIPT=build_matplotlibs.sh
    - env:
        - PY_VER=3.4
        - PLAT=i686
        - SCRIPT=build_matplotlibs.sh
    - env:
        - PY_VER=3.5
        - PLAT=i686
        - SCRIPT=build_matplotlibs.sh
    - env:
        - UNICODE_WIDTH=16
        - PY_VER=2.7
        - PLAT=i686
        - SCRIPT=build_matplotlibs.sh

before_install:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_$PLAT
  - docker pull $DOCKER_IMAGE

script:
  - if [ "$PLAT" == "i686" ]; then INTRO_CMD=linux32; fi
  - docker run --rm
    -e BUILD_SUFFIX="-$BLAS"
    -e UNICODE_WIDTH=$UNICODE_WIDTH
    -e BLAS_SOURCE=$BLAS
    -e PYTHON_VERSIONS=$PY_VER
    -e CYTHON_VERSIONS=$CYTHON_VERSIONS
    -e NUMPY_VERSIONS=$NUMPY_VERSIONS
    -e SCIPY_VERSIONS=$SCIPY_VERSIONS
    -e SCIKIT_LEARN_VERSIONS=$SCIKIT_LEARN_VERSIONS
    -e PANDAS_VERSIONS=$PANDAS_VERSIONS
    -e NUMEXPR_VERSIONS=$NUMEXPR_VERSIONS
    -e STATSMODELS_VERSIONS=$STATSMODELS_VERSIONS
    -e SCIKIT_IMAGE_VERSIONS=$SCIKIT_IMAGE_VERSIONS
    -e MATPLOTLIB_VERSIONS=$MATPLOTLIB_VERSIONS
    -v $PWD:/io
    $DOCKER_IMAGE $INTRO_CMD /io/$SCRIPT

before_deploy:
  - cp -r libraries-$BLAS/. wheelhouse-$BLAS
  - cd wheelhouse-$BLAS

deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
     secure: "Sy32flUDpCSlUyDgb6h+cCiD22N5RtxioPumT3cnGsHLPyufLvSFJn9L27ldONOcixAWY1rNHyfxEIPx+nH/fBW3XWG1wlNzsLGPRDaMCrKmRn/LKQ4bF9rsf3NC1AgcOtnAqwmUSNQczWB+jyDIJHjaRmlZN4yJ76VuHmNH0O+A7t05Cboi2yA2Di9iIFNFOCHvFmfysbkJ91o16tW9T+Yg3jeh9IURnJNr1DWAw5HvZ+jvLndhzo9QtU72IylnBeJJLDzHIqDiybNwz0QrRrqRhh/xTyusJF6+CciUre1mw3VLkzU5ExdBZMYES1/0KjmvMefF2xVNuFuFM+9xjfQsf/gxtcpMIfiiFQ9ZUhSX/hKaMFGX14T5TWfKfoykA8gp//e1i9D89qEiuEbtW3Sm7e4p3GmVMC1RcY7GHMrOsS6YhvqTbekMATuj0B2SbG942zSEsiEEJBiGFTC1u9AmPbAxUcjgtHQ0z9C/dkwsMVqujuC5TNQkTYlbNhKao8/z394dOF6B8J4VrGT2DKeEREan515NFh0cqoWx02J0Vs95F8GKjJ9rZ8WGdovrN6PnQR/UyWpIkMeKdZpKfMKTy4Vy1BdOlYiwWQcpWBhI665UBUNOqSwekpECZg+jzAMQYmOHFCTZ8i9wL15NF3Cs+wpADTo5D7OUJCWtrgQ="
  region: ORD
  container: manylinux-$BLAS$ATLAS_TYPE
  skip_cleanup: true
